### PR TITLE
Fix geo country cookie TypeError

### PR DESCRIPTION
**Pull request by RisingOrange**
`geo.country` from Netlify's edge function context is an object `{ code?: string; name?: string }`, not a string. This caused two bugs introduced in #695:

- **TypeError in production**: Passing the object as `SetCookie`'s `value` caused `quote()` to call `.includes()` on an object → `TypeError: t.includes is not a function`
- **Cookie reset on every page load**: Comparing the object to the string cookie value always evaluated to `true`, so the cookie was re-set and `selectBanners()` was called on every page visit

## Fix
Use `geo.country.code` (the string country code) instead of `geo.country` in both the comparison and the cookie value.

## Test plan

The geo API returns 501 in dev (no Netlify platform), so these can only be verified on a deploy preview:

- [ ] No `TypeError: t.includes is not a function` in the console
- [ ] The `geo_country` cookie is set to a country code string (e.g. `"US"`), not `[object Object]`

### CODE REVIEW

**Comment by Wituareard** [comment]
Thinking about whether we should check for `[object Object]` or maybe broader "invalid country code" for the people who visited in the meantime
